# users.models
MAX_LENGTH_USER_FIELD = 150
MAX_LENGTH_EMAIL = 254
ALLOWED_EXTENSIONS = ['jpg', 'jpeg', 'png']

# recipe.models
MAX_LENGTH_INGREDIENT_NAME = 128
MAX_LENGTH_MEASUREMENT_UNIT = 64
MAX_LENGTH_TAG_NAME = 32
MAX_LENGTH_TAG_SLUG = 32
MAX_LENGTH_RECIPE_NAME = 256


MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 500
MIN_INGRDEINTS_AMOUNT = 1
MAX_INGRDEINTS_AMOUNT = 32766
