# Generated by Django 3.2 on 2024-11-19 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20241118_1945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientAmount',
            new_name='RecipeIngredient',
        ),
    ]
